baseURL = "https://shaun.gg"
languageCode = "en"
theme = "adritian-free-hugo-theme"

[languages]
[languages.en]
disabled = false
languageCode = 'en'
languageDirection = 'ltr'
languageName = 'English'
title = 'Shaun Campbell'
weight = 0

[languages.en.menus]
# [[languages.en.menus.header]]
# disabled = true
# name = 'About'
# URL = '#about'
# weight = 2
# [[languages.en.menus.header]]
# disabled = true
# name = 'Portfolio'
# URL = '#portfolio'
# weight = 3
#  [[languages.en.menus.header]]
#  name = "Experience"
#  URL = "#experience"
#  weight = 4

# [[languages.en.menus.header]]
# name = "Blog"
# URL = "/blog"
# weight = 5

# [[languages.en.menus.header]]
# name = "Contact"
# URL = "#contact"
# weight = 6

# [[languages.en.menus.footer]]
# name = "About"
# URL = "#about"
# weight = 2

# [[languages.en.menus.footer]]
# name = "Portfolio"
# URL = "#portfolio"
# weight = 3

# [[languages.en.menus.footer]]
# name = "Contact"
# URL = "#contact"
# weight = 4

# Plugins
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/rad-icons.css"
[[params.plugins.css]]
URL = "css/custom.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/rad-animations.js"
[[params.plugins.js]]
URL = "js/sticky-header.js"
[[params.plugins.js]]
URL = "js/library/fontfaceobserver.js"

# SCSS Plugins
[[params.plugins.scss]]
URL = "css/menu.scss"

[params]

sections = [
    "showcase",
    "about",
    "education",
    "experience",
    "client-and-work",
    "testimonial",
    "contact",
    "newsletter",
]

homepageExperienceCount = 6

# controls vercel page insights - disabled by default
vercelPageInsights = false
vercelAnalytics = false

[params.google_analytics]
code = "UA-XXXXX-Y"
enabled = false
[params.google_tag_manager]
code = "GTM-XXXXX"
enabled = false
